### ISSUE TITLE
incompatibility with Gradle 5.1

### ISSUE THREAD

**Issue by carloxavier** [fourlastor/pickle#4]
When using the AndroidStudio 3.4 Canary 10,
and having upgraded to Gradle 5.1-milestone-1,

the following error appears while building:

```
Caused by: java.lang.NoSuchMethodError: com.android.build.gradle.tasks.MergeSourceSetFolders.getOutputDir()Ljava/io/File;
	at com.fourlastor.pickle.PicklePlugin$configure$1.execute(PicklePlugin.kt:115)
	at com.fourlastor.pickle.PicklePlugin$configure$1.execute(PicklePlugin.kt:23)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
	at com.fourlastor.pickle.PicklePlugin.configure(PicklePlugin.kt:109)
	at com.fourlastor.pickle.PicklePlugin.access$configure(PicklePlugin.kt:23)
	at com.fourlastor.pickle.PicklePlugin$apply$1$1.execute(PicklePlugin.kt:96)
	at com.fourlastor.pickle.PicklePlugin$apply$1$1.execute(PicklePlugin.kt:23)
	at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:158)
	at com.fourlastor.pickle.PicklePlugin$apply$1.execute(PicklePlugin.kt:87)
	at com.fourlastor.pickle.PicklePlugin$apply$1.execute(PicklePlugin.kt:23)

```

**Comment by tasomaniac** [comment]
The issue comes from Android Gradle plugin 3.4. Just opened a ticket for them https://issuetracker.google.com/issues/122883574

Considering 3.4 is now in beta, I don't think this will change. And supporting both versions is not easy since their signature changes.
